
format_version: '1.0'

input_files: 'KroeningSharyginaTsitovichWintersteiger-2010CAV-Fig1_true-termination.c_Iteration1_Lasso_4-phaseTemplate.smt2'

properties:
  - property_file: ../../properties/sat.prp
    expected_verdict: false
    
