
format_version: '1.0'

input_files: 'HarrisLalNoriRajamani-SAS2010-Fig1_true-termination.c_Iteration2_Lasso+nonterminationTemplate_0.smt2'

properties:
  - property_file: ../../properties/sat.prp
    expected_verdict: false
    
