
format_version: '1.0'

input_files: 'PodelskiRybalchenko-VMCAI2004-Ex1_true-termination.c_Iteration6_Loop+nonterminationTemplate_0.smt2'

properties:
  - property_file: ../../properties/sat.prp
    expected_verdict: false
    
