
format_version: '1.0'

input_files: 'b.13-alloca_true-termination.c.i_Iteration1_Lasso+nonterminationTemplate.smt2'

properties:
  - property_file: ../../properties/sat.prp
    expected_verdict: false
    
